delpoy:
  provider: pages
  skip_cleanup: true
  github_token: obx8Rq5kskRyNgCvibyq
  on:
    branch: master
  github_url: blog.xheldon.com
script: npm run build
language: node_js
node_js:
  - "iojs"
  - "6"
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=prod
