delpoy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  github_url: blog.xheldon.com
script: npm run build
language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
env:
    - NODE_ENV=prod
after_success:
    - cd docs
    - git init
    - git checkout -b gh-pages
    - git add .
    - git -c user.name='travis' -c user.email='travis' commit -m init
    - git push -f -q https://Xheldon:$GITHUB_API_KEY@github.com/Xheldon/framework-all-in-one-blog gh-pages
